# Generated by Django 4.0.5 on 2022-06-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Animal',
        ),
    ]
